name: miladtech_delta_markdown
version: 1.0.0

description: A library for converting between Markdown and Delta of the
  package flutter_quill.
homepage: https://github.com/mrmostafaei/miladtech_delta_markdown

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  args: ^2.0.0
  charcode: ^1.3.1
  collection: ^1.15.0
  flutter_quill: ^7.2.9

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  test: ^1.16.5
